#!/bin/sh

CONFIG_NAME=$(basename $0 .sh)

TRILINOS_HOME=`pwd`/trilinos
BUILD_DIR=`pwd`/build/$CONFIG_NAME
INSTALL_DIR=`pwd`/install/$CONFIG_NAME

EXTRA_ARGS=$@

if [ -e $BUILD_DIR ]; then 
    echo Error: $BUILD_DIR already exist. 
fi

mkdir -p $BUILD_DIR
cd $BUILD_DIR

#rm CMakeCache.txt

# create a trilinos-version file which contains the git hash of the last commit
pushd $TRILINOS_HOME
echo `git log -n 1| head -n 3` > $BUILD_DIR/trilinos-version
popd

cmake3 \
    -D CMAKE_BUILD_TYPE:STRING=DEBUG \
    -D BUILD_SHARED_LIBS:BOOL=ON \
    -D TPL_ENABLE_MPI:BOOL=OFF \
\
    -D CMAKE_INSTALL_PREFIX:STRING=$INSTALL_DIR \
    -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
    -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
    -D CMAKE_C_COMPILER:STRING="/opt/clang/bin/clang" \
    -D CMAKE_CXX_COMPILER:STRING="/opt/clang/bin/clang++" \
    -D CMAKE_AR:STRING="/opt/clang/bin/llvm-ar" \
    -D CMAKE_LINKER:STRING="/opt/clang/bin/llvm-ld" \
    -D CMAKE_NM:STRING="/opt/clang/bin/llvm-nm" \
    -D CMAKE_OBJDUMP:STRING="/opt/clang/bin/llvm-objdump" \
    -D CMAKE_RANLIB:STRING="/opt/clang/bin/llvm-ranlib" \
    -D CMAKE_SHARED_LINKER_FLAGS:STRING="-Wl,--no-undefined" \
\
    -D Trilinos_ENABLE_Fortran=OFF \
    -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION:BOOL=ON \
    -D Trilinos_ENABLE_OpenMP:BOOL=OFF \
    -D Trilinos_ENABLE_KokkosCore:BOOL=ON \
    -D Trilinos_ENABLE_KokkosAlgorithms:BOOL=ON \
\
    -D Trilinos_ENABLE_MueLu:BOOL=ON \
    -D Xpetra_ENABLE_Experimental:BOOL=ON \
    -D Xpetra_ENABLE_TESTS:BOOL=ON \
    -D MueLu_ENABLE_Experimental:BOOL=OFF \
    -D MueLu_ENABLE_EXAMPLES:BOOL=OFF \
    -D MueLu_ENABLE_TESTS:BOOL=OFF \
\
    -D Trilinos_ENABLE_Epetra:BOOL=ON \
    -D Trilinos_ENABLE_EpetraExt:BOOL=ON \
    -D Trilinos_ENABLE_Isorropia:BOOL=ON  \
    -D Trilinos_ENABLE_Zoltan:BOOL=ON  \
    -D Trilinos_ENABLE_Zoltan2:BOOL=ON  \
    -D Trilinos_ENABLE_Teko:BOOL=ON \
    -D Trilinos_ENABLE_Belos:BOOL=ON \
    -D Trilinos_ENABLE_AztecOO:BOOL=ON \
    -D Trilinos_ENABLE_Panzer:BOOL=ON \
    -D Trilinos_ENABLE_Shards:BOOL=ON \
    -D Trilinos_ENABLE_Sacado:BOOL=ON \
    -D Trilinos_ENABLE_Intrepid:BOOL=ON \
    -D Trilinos_ENABLE_Stratimikos:BOOL=ON \
    -D Stratimikos_ENABLE_TESTS:BOOL=ON \
    -D Stratimikos_ENABLE_EXAMPLES:BOOL=ON \
    -D Trilinos_ENABLE_ML:BOOL=ON \
    -D Trilinos_ENABLE_FEI:BOOL=OFF \
    -D Trilinos_ENABLE_Amesos:BOOL=ON \
    -D Trilinos_ENABLE_Amesos2:BOOL=ON \
    -D Trilinos_ENABLE_SEACAS:BOOL=ON \
    -D Trilinos_ENABLE_SEACASIoss:BOOL=ON \
    -D Trilinos_ENABLE_Galeri:BOOL=ON \
    -D Trilinos_ENABLE_Ifpack2:BOOL=ON \
    -D Trilinos_ENABLE_Stokhos:BOOL=OFF \
     \
    -D Trilinos_ENABLE_SEACAS:BOOL=OFF \
    -D Panzer_ENABLE_TESTS:BOOL=OFF \
    -D Panzer_ENABLE_EXAMPLES:BOOL=OFF \
    -D EpetraExt_ENABLE_HDF5:BOOL=OFF \
    -D Teuchos_ENABLE_LONG_LONG_INT:BOOL=OFF \
    -D Intrepid_ENABLE_DEBUG_INF_CHECK=OFF \
    -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION=ON \
        -D Teuchos_ENABLE_COMPLEX=OFF \
        -D Teuchos_ENABLE_LONG_LONG_INT=OFF \
        -D Tpetra_INST_INT_INT=ON \
        -D Tpetra_INST_INT_UNSIGNED=OFF \
        -D Tpetra_INST_INT_LONG=OFF \
        -D Tpetra_INST_INT_LONG_LONG=OFF \
        -D Tpetra_INST_DOUBLE=ON \
        -D Tpetra_INST_FLOAT=OFF \
        -D Tpetra_INST_COMPLEX_DOUBLE=OFF \
        -D Tpetra_INST_COMPLEX_FLOAT=OFF \
        -D Tpetra_INST_SERIAL=ON \
        -D Tpetra_INST_OPENMP:BOOL=OFF \
        -D Kokkos_ENABLE_Serial:BOOL=ON \
        -D Kokkos_ENABLE_OpenMP:BOOL=OFF \
        -D Kokkos_ENABLE_Pthread:BOOL=OFF \
        -D Xpetra_Epetra_NO_32BIT_GLOBAL_INDICES=OFF \
        -D Xpetra_Epetra_NO_64BIT_GLOBAL_INDICES=ON \
        -D Teko_USE_LONGLONG_GO:BOOL=OFF \
\
    -D Teuchos_ENABLE_LONG_LONG_INT:BOOL=OFF \
\
    -D Trilinos_ENABLE_INSTALL_CMAKE_CONFIG_FILES:BOOL=OFF \
    -D Trilinos_DEPS_XML_OUTPUT_FILE:FILEPATH="" \
\
    $EXTRA_ARGS \
    ${TRILINOS_HOME}
